---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - debug: msg="Moving files to remote_server"
    - copy: src=files/{{item}} dest=/tmp/{{item}}
      with_items:
        - filemove.sh
        - filemove1.sh

    - name: moving correct file
      command: /bin/sh /tmp/filemove1.sh
      register: file_status

    - debug: msg="file move status {{file_status.stdout}}"

    - name: moving error file location
      command: /bin/sh files/filemove.sh
      register: file1_status
      when: file_status.stdout == 0

    - debug: msg="file1 move status {{file1_status.stdout | default('NA')}}"

    - set_stats:
        data:
          first_file_status: "{{ file_status.stdout | default('NA') }}"
          second_file_status: "{{ file1_status.stdout | default('NA') }}"

